baseURL = "https://littlesunfarm.com"
languageCode = "en-us"
title = "Little Sun Farm"
theme = "timer"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Gallery"
        url     = "gallery"
        weight  = 1
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Contact"
        url     = "contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    dateFormat = "6 January 2006"
    #
    # You can use either an image or text as logo.
    # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
    # To use text as logo use 'logo_text'
    logo = "images/logo.png"
    logo_alt = ""
    logo_text = "Little Sun Farm"

    # Banner Section
    [params.banner]
        enable  = true
        heading = "LITTLE SUN FARM"
        description = "Little Sun Farm grows diversified vegetables on less than 1 acre, and sells at farmers markets in the Portland metro area. Check back in spring for 2020 farmers market information."
        btn     = false
        btnText = "Download More"
        btnURL  = "https://themefisher.com/"
            [[params.banner.flipText]]
                title   = "GRESHAM, OR"
        [[params.banner.flipText]]
            title   = "1/3 ACRE"
        [[params.banner.flipText]]
            title   = "FEMALE & NATIVE-OWNED"
        [[params.banner.flipText]]
            title   = "EST 2019"
          [[params.banner.flipText]]
            title   = "FOLLOW ON INSTAGRAM @LITTLESUNFARM"


    # Homepage About Section
    [params.about]
        enable  = false
        title   = "Under Construction"
        content = "Brand new website, come back soon."
        image   = ""

    # Call to Action
    [params.cta]
        enable  = false
        title   = "Follow on Instagram!"
        content = "Stay in the loop. See what's happening on the farm."
        btnText = "Contact me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Recent Updates"
        subtitle= "Follow me while I get new ground up and running."

    # Footer section
    [params.footer]
        site_url = "https://littlesunfarm.com"
        copyright_owner = "Little Sun Farm, LLC"
        [[params.footer.social]]
            class = "email"
            icon = "ion-ios-email"
            link = "mailto:reiden@littlesunfarm.com"
        [[params.footer.social]]
            class = "instagram"
            icon = "ion-social-instagram"
            link = "https://www.instagram.com/littlesunfarm/"

    [params.contact]
        [[params.contact.social]]
            icon = "ion-ios-email-outline"
            link = "mailto:reiden@littlesunfarm.com"
            text = "reiden@littlesunfarm.com"
            text2 = ""
        [[params.contact.social]]
            icon = "ion-ios-telephone-outline"
#text = "+1 503 484 4200"
        [[params.contact.social]]
            icon = "ion-social-instagram-outline"
            link = "https://www.instagram.com/littlesunfarm/"
            text = "littlesunfarm"
