baseURL = "https://littlesunfarm.com"
languageCode = "en-us"
title = "Little Sun Farm, LLC"
theme = "timer"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    dateFormat = "6 January 2006"
    #
    # You can use either an image or text as logo.
    # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
    # To use text as logo use 'logo_text'
    logo = "images/logo.png"
    logo_alt = ""
    logo_text = "Little Sun Farm, LLC"

    # Banner Section
    [params.banner]
        enable  = false
        bgImage = "images/slider.jpg"
        heading = "HI, MY NAME IS REIDEN & I AM A"
        description = "WITH 10 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING DIGITAL DESIGN DIRECTOR, WEB DESIGNER AND DEVELOPER. THIS SITE SHOWCASES SOME OF MY WORK."
        btn     = true
        btnText = "Download More"
        btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "FARMER"
        [[params.banner.flipText]]
            title   = "DREAMER"
        [[params.banner.flipText]]
            title   = "CAT LOVER"
        [[params.banner.flipText]]
            title   = "NE PORTLAND RESIDENT"
        [[params.banner.flipText]]
            title   = "NATIVE"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "Under Construction"
        content = "Brand new website, come back soon."
        image   = ""

    # Call to Action
    [params.cta]
        enable  = false
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Recent Updates"
        subtitle= "Follow me while I get new ground up and running."

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Footer section
    [params.footer]
        site_url = "https://littlesunfarm.com"
        copyright_owner = "Little Sun Farm, LLC"
        [[params.footer.social]]
            class = "email"
            icon = "ion-ios-email"
            link = "mailto:reiden@littlesunfarm.com"
        [[params.footer.social]]
            class = "instagram"
            icon = "ion-social-instagram"
            link = "https://www.instagram.com/littlesunfarm/"

    [params.contact]
        [[params.contact.social]]
            icon = "ion-ios-email-outline"
            link = "mailto:reiden@littlesunfarm.com"
            text = "reiden@littlesunfarm.com"
            text2 = ""
        [[params.contact.social]]
            icon = "ion-ios-telephone-outline"
            text = "+1 503 484 4200"
        [[params.contact.social]]
            icon = "ion-social-instagram-outline"
            link = "https://www.instagram.com/littlesunfarm/"
            text = "littlesunfarm"

